- hosts: localhost
  connection: local
  tasks: 
  - shell: aws ec2 describe-volume-status --volume-ids {{ item }}
    with_items:
    - "{{ instances }}"
    #- "{{ instance2 }}"
    #- "{{ instance3 }}"
    failed_when: " 'end of statement block' in item "
    register: op
    ignore_errors: true
  - debug: var=op
    #debug: msg="{{ op.stdout_lines }}"
